adding find and auto find
fixes #2

diff --git a/bvimp b/bvimp
--- a/bvimp
+++ b/bvimp
@@ -5,18 +5,84 @@ set -f
 source "json.bash"
 
 declare -r REPOSITORY_REGEX='^([a-zA-Z0-9_-]+)/([a-zA-Z0-9_.-]+)$'
-declare -r NAME_REGEX='^[a-zA-Z0-9_-]+$'
+declare -r NAME_REGEX='^[a-zA-Z0-9_.-]+$'
+declare -r NUMBER_REGEX='^0|[1-9][0-9]*$'
 declare BVIMP_HOME="$HOME/.vim/pack/bvimp"
 
 getLocalPackageData() {
+  local LOCAL="${LOCAL-false}"
   local user
   local repository
+  local -A potentialRepos
+  local -a order
   for package in "$@"; do
+    if "$interactive" && [[ "$package" =~ $NAME_REGEX ]]; then
+      if "$LOCAL"; then
+        order=( $(git config --file "$BVIMP_HOME/.gitmodules" --get-regexp "/$package"'@[^@\/]+.path$'  | awk '{print gensub(/^start\/([^@]+)@(.*)/, "\\2/\\1", 1, $2)}') )
+        if [[ "${#order[@]}" -gt 0 ]]; then
+          while true; do
+            printf "Found multiple packages for: %s\n" "$package" >&2
+            for ((i=0; i < ${#order[@]}; i++)); do
+              printf "\t%d: %s\n" "$i" "${order[$i]}" >&2
+            done
+            printf "Choose an option [0-%d,s,q](default: 0): " "${#order[@]}" >&2
+            if read -r response; then
+              if [[ -z "$response" ]]; then
+                package="${order[0]}"
+                break
+              elif [[ "$response" == "s" ]]; then
+                continue 2
+              elif [[ "$response" == "q" ]]; then
+                return 1
+              elif [[ "$response" =~ $NUMBER_REGEX ]]; then
+                package="${order[$response]}"
+              fi
+            else
+              continue 2
+            fi
+          done
+        else
+          invalidPackages["$package"]="No packages found with the name"
+          continue
+        fi
+
+      else
+        potentialRepos=() 
+        order=()
+        bvimp_findRepos potentialRepos order "$package"
+        if [[ "${#order[@]}" -gt 0 ]]; then
+          while true; do
+            printf "Found multiple packages for: %s\n" "$package" >&2
+            for ((i=0; i < ${#order[@]}; i++)); do
+              printf "\t%d: %s\n" "$i" "${potentialRepos[${order[$i]}]}" >&2
+            done
+            printf "Choose an option [0-%d,s,q](default: 0): " "${#order[@]}" >&2
+            if read -r response; then
+              if [[ -z "$response" ]]; then
+                package="${order[0]}"
+                break
+              elif [[ "$response" == "s" ]]; then
+                continue 2
+              elif [[ "$response" == "q" ]]; then
+                return 1
+              elif [[ "$response" =~ $NUMBER_REGEX ]]; then
+                package="${order[$response]}"
+              fi
+            else
+              continue 2
+            fi
+          done
+        else
+          invalidPackages["$package"]="No packages found with the name"
+          continue
+        fi
+      fi
+    fi
+
     if [[ -z "${packageStrings[$package]+_}" ]]; then
       if [[ "$package" =~ $REPOSITORY_REGEX ]]; then
         user="${BASH_REMATCH[1]}"
         repository="${BASH_REMATCH[2]}"
-
         packageStrings["$package"]="$repository@$user"
       else
         invalidPackages["$package"]="Invalid Package specified"
@@ -31,7 +97,7 @@ validatePackageData() {
   done
 
   if [[ "${#invalidPackages[@]}" -gt 0 ]]; then
-    printf "No packages installed\n" >&2
+    printf "No packages modified\n" >&2
     return 1
   fi
 }
@@ -81,6 +147,7 @@ bvimp_add() {
         printf "Package named %s already exists\n" "$target" >&2
         return 1
       fi
+      printf "Installing package: %s\n" "$target" >&2
       (
         cd "$BVIMP_HOME"
         # TODO this can fail...
@@ -100,7 +167,7 @@ bvimp_remove() {
   local repoName
   local repoPath
   for target in "${!packageStrings[@]}"; do
-
+    printf "Removing package: %s\n" "$target" >&2
     repoName="${packageStrings[$target]}"
     repoPath="start/$repoName"
     if [[ ! -d "$BVIMP_HOME/$repoPath" ]]; then
@@ -133,9 +200,62 @@ bvimp_list() {
     | awk '{ printf("%s\t%s\n", gensub(/.*\/([^\/@]+)@([^\/@]+)\.url$/, "\\2/\\1", 1, $1), $2) }'
 }
 
+# Searches for repositories with the exact name specified
+#
+# Assumes that the specified repository is valid.
+bvimp_findRepos() {
+  local -n _results="$1"
+  local -n _order="$2"
+  local -r repository="$3"
+
+  local name
+  local infoString
+  local -A queryResults=()
+
+  tmpFile="$(mktemp -t 'bvimp.XXXX.json')"
+  code="$(curl -s -w '%{http_code}' -o "$tmpFile" "https://api.github.com/search/repositories?q=$repository+in:name")"
+  parseJson queryResults <"$tmpFile" 
+  rm "$tmpFile"
+  if [[ "$code" == 200 ]]; then
+    local -i items="${queryResults[./items/\#]}"
+    for ((i=0; i < items; i++)); do
+      if [[ "${queryResults[./items/$i/name]}" == "$repository" ]]; then
+        name="${queryResults[./items/$i/full_name]}"
+        printf -v infoString "%s (%d stars)" "$name" "${queryResults[./items/$i/stargazers_count]}"
+        _results["$name"]="$infoString"
+        _order+=( "$name" )
+      fi
+    done
+  else
+    return 1
+  fi
+}
+
+bvimp_find() {
+  local -r repository="$1"
+  if [[ "$repository" =~ $NAME_REGEX ]]; then
+    local -A potentialRepos
+    local -a order
+    
+    bvimp_findRepos potentialRepos order "$repository"
+    for name in "${order[@]}"; do
+      printf "%s\n" "${potentialRepos[$name]}"
+    done
+  else
+    printf "Invalid repository name: %s\n" "$repository" >&2
+    return 1
+  fi
+}
+
 main() {
   local -A packageStrings
   local -A invalidPackages
+  local interactive
+  if [[ -t 1 ]]; then
+    interactive=true
+  else
+    interactive=false
+  fi
   if [[ "$#" -gt 0 ]]; then
     # TODO command parsing
     #
@@ -153,13 +273,15 @@ main() {
         checkInstall || exit 1
         shift
         getLocalPackageData "$@"
+        [[ $? == 0 ]] || exit 1
         validatePackageData || exit 1
         bvimp_add
         ;;
       remove)
         checkInstall || exit 1
         shift
-        getLocalPackageData "$@"
+        LOCAL=true getLocalPackageData "$@"
+        [[ $? == 0 ]] || exit 1
         validatePackageData || exit 1
         bvimp_remove
         ;;
@@ -171,6 +293,10 @@ main() {
       list)
         checkInstall || exit 1
         bvimp_list
+        ;;
+      find)
+        shift
+        bvimp_find "$1"
         ;;
       init)
         bvimp_init
